---
permalink: administration/reference_citrix_xen_plug_in.html 
sidebar: sidebar 
keywords: snap, creator, support, backup, restore, citrix, xenserver, virtual, machine, vm, citrix, xenserver, plug-in 
summary: Snap Creator prend en charge la sauvegarde et la restauration des machines virtuelles Citrix XenServer grâce au plug-in Citrix XenServer. 
---
= Plug-in Citrix XenServer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator prend en charge la sauvegarde et la restauration des machines virtuelles Citrix XenServer grâce au plug-in Citrix XenServer.


NOTE: Pour obtenir les dernières informations sur le support ou les matrices de compatibilité, consultez la matrice d'interopérabilité.

Le plug-in Citrix XenServer prend en charge Windows et XenServer.

Tenez compte des points suivants lorsque vous utilisez le plug-in Citrix XenServer :

* Le serveur Active IQ Unified Manager en tant que proxy n'est pas pris en charge.
* Les opérations de montage, de démontage et de sauvegarde effectuées à l'aide d'Open Systems SnapVault et de gestion des journaux d'archivage ne sont pas prises en charge.
* Les opérations de restauration de volumes ne sont pas prises en charge ; seules les opérations de restauration définies par l'application sont prises en charge.
* Les VM supprimées peuvent être restaurées.
* Snap Creator Agent doit être installé sur l'hôte sur lequel XenCenter est installé et Snap Creator Server ne doit pas être installé sur XenServer.
* La valeur SC_AGENT_TIMEOUT doit être supérieure à la valeur par défaut : 600 ou supérieure.
* Si la valeur DE APP_DEFINED_RESTORE est y, l'opération de restauration SnapVault à l'aide de l'interface utilisateur n'est pas prise en charge.
* Si le maître de pool tombe en panne dans un pool de serveurs, le fichier de configuration Snap Creator doit être modifié manuellement avec le nouveau serveur maître pour une plus grande activité.
* Les outils XenServer doivent être installés sur toutes les machines virtuelles.
* Pour Fibre Channel dans un environnement SAN (Storage Area Network), l'outil plink.exe doit être installé sur un hôte sur lequel Snap Creator Agent est installé, et le chemin plink.exe doit être ajouté à la variable d'environnement système.
+
Pour plus d'informations sur l'ajout du chemin plink.exe à la variable d'environnement système, reportez-vous au _Snap Creator Framework installation Guide_.

* Les opérations de pause et de non-pause de la machine virtuelle sont effectuées en série.
+
Pour plusieurs machines virtuelles, la durée de la machine virtuelle en pause lors de l'opération de sauvegarde dépend du nombre de machines virtuelles.

* La découverte automatique des volumes est prise en charge.




== Configurations Citrix XenServer prises en charge

Les configurations Citrix XenServer suivantes sont prises en charge :

* SAN
+
** Prise en charge des machines virtuelles invitées avec une image de disque virtuel (VDI) par référentiel de stockage.
** Prend en charge les disques de données avec une VDI par référentiel de stockage


* NAS
+
** Prend en charge les machines virtuelles invitées installées sur des montages NFS.
** Prend en charge les disques de données sur des montages NFS.






== Paramètres

Le tableau suivant répertorie et décrit les paramètres du plug-in Citrix XenServer :

|===


| Paramètre | Réglage | Description 


 a| 
XEN_VMS
 a| 
Adresse IP de l'hôte : VM#
 a| 
Répertorie les machines virtuelles d'un hôte particulier, séparées par une barre oblique (/). Par exemple : 10.10.10.192:VM1/VM2/VM3



 a| 
XEN_HOST_USERS
 a| 
Adresse IP de l'hôte:nom d'utilisateur/mot de passe
 a| 
Répertorie les hôtes Xen ainsi que le nom d'utilisateur et le mot de passe correspondants.



 a| 
XEN_BIN_PATH
 a| 
Par exemple : c:\Program Files\Citrix\XenCenter\xe.exe
 a| 
Spécifie le chemin d'accès de l'exécutable XenServer (xe). La console XenCenter est requise pour l'importation et l'exportation des métadonnées de machine virtuelle.



 a| 
CHEMIN_MÉTADONNÉES_XEN
 a| 
Par exemple : c:\scmetadata
 a| 
Spécifie le chemin sur le serveur sur lequel vous pouvez télécharger les métadonnées de la machine virtuelle.



 a| 
XEN_RESTORE_VMS
 a| 
Par exemple : xenserver1:vm1,vm2;xenserver2:vm1,vm2
 a| 
Contient les machines virtuelles à restaurer. Ce paramètre n'est requis que lors d'une opération de restauration.

|===
*Informations connexes*

http://mysupport.netapp.com/matrix["Matrice d'interopérabilité : mysupport.netapp.com/matrix"]
