---
permalink: administration/reference_cli_command_for_snap_creator_rbac_actions.html 
sidebar: sidebar 
keywords: snap, creator, rbac, cli, command, user, access 
summary: 'Vous pouvez effectuer des actions Snap Creator RBAC à l"aide des commandes CLI.' 
---
= Commandes permettant de gérer l'accès des utilisateurs Snap Creator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer des actions Snap Creator RBAC à l'aide des commandes CLI.

Le tableau suivant fournit l'équivalent de ligne de commande pour les actions RBAC basées sur une interface graphique Snap Creator :

|===
| Zone RBAC | Action | Commande et paramètres associés 


 a| 
Utilisateurs
 a| 
Créez un nouvel utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userAdd
--username user_name
--userPwd user_passwd
--verbose
----


 a| 
Supprimer un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userDelete
--username user_name
--verbose
---- a| 
Répertorier tous les utilisateurs.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userList
--verbose
---- a| 
Répertorier tous les utilisateurs affectés pour un rôle.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userListAssigned
--roleName role_name
--verbose
----


 a| 
Répertorie tous les utilisateurs affectés à un profil.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action userListForProfile
--verbose
---- a| 
Rôles



 a| 
Créer un nouveau rôle.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleAdd
--roleName role_name
--roleDesc role_description
--verbose
---- a| 
Supprimer un rôle.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleDelete
--roleName role_name
--verbose
---- a| 
Attribuez un rôle à un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleAssign
--userName user_name
--roleName role_name
--verbose
----


 a| 
Annuler l'affectation d'un rôle à un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleUnassign
--userName user_name
--roleName role_name
--verbose
---- a| 
Répertorie tous les rôles attribués à un utilisateur.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleListAssigned
--userName user_name
--verbose
---- a| 
Autorisations
 a| 
Créez une nouvelle autorisation.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permAdd
--permName permission_name
--permDesc permission_description
--verbose
---- a| 
Supprimer une autorisation.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permDelete
--permName permission_name
--verbose
----


 a| 
Attribuez une autorisation à un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permAssign
--permName permission_name
--roleName role_name
--verbose
---- a| 
Annuler l'attribution d'une autorisation à un utilisateur.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permUnaspermission_namesign
--permName
--roleName role_name
--verbose
---- a| 
Répertorier toutes les autorisations.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permList
--verbose
----


 a| 
Répertorier toutes les autorisations attribuées à un rôle.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permListAssigned
--roleName role_name
--verbose
---- a| 
Exploitation



 a| 
Attribuez une opération à une autorisation.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opAssign
--opName operation_name
--permName permission_name
--verbose
---- a| 
Annuler l'affectation d'une opération d'une autorisation.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opUnassign
--opName operation_name
--permName permission_name
--verbose
---- a| 
Répertorier toutes les opérations.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opList
--verbose
----


 a| 
Répertorier toutes les opérations affectées à une autorisation.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opListAssigned
--permName permission_name
--verbose
---- a| 
Profils



 a| 
Attribuer un profil à un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileAssign
--userName user_name
--verbose
---- a| 
Annuler l'affectation d'un profil à un utilisateur.



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileUnassign
--userName user_name
--verbose
---- a| 
Répertorie tous les profils affectés à un utilisateur.
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action profileListForUser
--userName user_name
--verbose
----
|===