---
permalink: administration/reference_guidelines_for_using_the_snap_creator_command_line.html 
sidebar: sidebar 
keywords: snap, creator, command-line, functionality, gui, cli, backup, lun 
summary: 'Snap Creator offre une fonctionnalité de ligne de commande qui vous permet d"effectuer diverses actions sans utiliser l"interface utilisateur graphique. Par exemple, vous pouvez créer une copie de sauvegarde, un volume clonea ou un LUN et importer des fichiers de configuration à partir de l"interface de ligne de commande (CLI).' 
---
= Instructions d'utilisation de l'interface de ligne de commandes Snap Creator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator offre une fonctionnalité de ligne de commande qui vous permet d'effectuer diverses actions sans utiliser l'interface utilisateur graphique. Par exemple, vous pouvez créer une copie de sauvegarde, un volume clonea ou un LUN et importer des fichiers de configuration à partir de l'interface de ligne de commande (CLI).

Pour afficher une liste complète de toutes les commandes et des paramètres associés, vous devez exécuter Snap Creator à l'invite de commande sans arguments : /install_path/scServer/snapcreator

[listing]
----
[root@lyon scServer4.3.0]# ./snapcreator
Usage: ./snapcreator --server <IP> --port <Port> --user <User> --passwd <Passwd> --profile <Profile> --config <Config> --action <Action> --policy <Policy> <Optional Arguments>

Connection Information
  --server <IP|Hostname>     The IP address or hostname of the Snap Creator server
  --port <number>            The port number of the Snap Creator server
  --user <user>              The username used for Snap Creator server authentication
  --passwd <password>        The password used for Snap Creator server authentication

Configuration Information
  --profile <Profile>        The profile you want to run
                             Profiles are dir's located under configs dir
                             Uses default config, unless --config is specified
  list                       Displays all configurations known to Snap Creator

 Workflow Actions
  --action <Action>          The action you want Snap Creator to perform
  backup                     Takes a backup using NetApp storage technology
  ossv                       Uses OSSV to perform the backup, no primary backup is taken
  cloneLun                   In addition to backup will clones lun(s)
                             using lun clone
  cloneVol                   In addition to backup will clones volume
                             using vol clone
  cloneDel                   Deletes vol clones outside of normal workflow
  clone                      Performs a plug-in driven clone operation

  restore                    Enters an interactive restore menu for a given
                             Snap Creator policy, you can choose a file or volume restore

  backupDel                  Enters an interactive backup delete menu for a given
                             Snap Creator policy
  backupList                 Lists all backups under Snap Creator control
  volumeList                 Lists all volumes under Snap Creator control
  cloneList                  Lists all volume clones under Snap Creator control
  dpstatus                   Shows the snapvault/snapmirror status
  pmsetup                    Creates a Protection Manager DataSet for given config
  arch                       Does not take backup, only performs
                             archive log management
  quiesce                    Does not take backup, only performs
                             quiesce for given application defined in APP_NAME
  unquiesce                  Does not take backup, only performs
                             unquiesce for given application defined in APP_NAME
  discover                   Does not take backup, only performs
                             discover for given application defined in APP_NAME
  mount                      Clone an existing backup and provide optional mount commands
  umount                     Clone an existing backup and provide optional umount commands
  scdump                     Dumps logs, configs, and support information for a given profile
                             in a zip file called scdump located under Snap Creator root directory
  custom                     A plug-in may define a custom action
  dispatch                   Executes any Snap Creator workflow that exists
  ...
----
Si le nom d'utilisateur ou le mot de passe incorrect est fourni lors de l'utilisation de l'interface de ligne de commande Snap Creator, le message d'erreur suivant s'affiche : 403 interdit ----- Le nom d'utilisateur et le mot de passe ne sont pas corrects
