---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: 'Vous pouvez personnaliser le magasin de clés ou le certificat par défaut à l"aide de la commande keytool disponible sur Windows et UNIX.' 
---
= Personnalisation du magasin de clés par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez personnaliser le magasin de clés ou le certificat par défaut à l'aide de la commande keytool disponible sur Windows et UNIX.

La commande keytool est fournie par Java. Dans certains environnements, vous devrez peut-être passer au répertoire d'installation Java pour exécuter la commande keytool.

Snap Creator ne prend pas en charge les magasins de confiance.

. Arrêtez l'agent Snap Creator.
. Générer un nouveau magasin de clés avec un seul certificat :
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
Keytool -genkeypair -alias servicekey -keystore serviceKeystore.jks -kepass kypswd123 -storepass kystrpswd123

. Copiez le fichier keystore dans le répertoire sgAgent4.3.0/etc/.
. Mettez à jour les paramètres KEYSTORE_FILE=keystore_file et KEYSTORE_PASS=keystore Password dans le fichier de configuration de l'agent Snap Creator (scrog4.3.0/etc/allowed_commands.config).
. Démarrez Snap Creator Agent.


*Informations connexes*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Démarrage, vérification et arrêt de Snap Creator Agent sous Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Démarrage, vérification et arrêt de Snap Creator Agent sous UNIX]
