---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: 'Vous pouvez stocker les informations d"identification Snap Creator Server (telles que le nom d"hôte du serveur ou l"adresse IP, le port, l"utilisateur et le mot de passe) pour éviter de saisir plusieurs fois les informations d"identification sur l"interface de ligne de commande. Si nécessaire, vous pouvez supprimer les informations d"identification stockées.' 
---
= Définition des informations d'identification Snap Creator Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez stocker les informations d'identification Snap Creator Server (telles que le nom d'hôte du serveur ou l'adresse IP, le port, l'utilisateur et le mot de passe) pour éviter de saisir plusieurs fois les informations d'identification sur l'interface de ligne de commande. Si nécessaire, vous pouvez supprimer les informations d'identification stockées.

La procédure de configuration des identifiants Snap Creator Server est la même pour Windows et UNIX. La procédure suivante utilise des exemples de l'environnement UNIX.

. Sur l'hôte sur lequel Snap Creator Server est installé, entrez la commande suivante à partir du répertoire d'installation de Snap Creator Server :
+
`/install_path/scServer4.3/snapcreator --credentials`

+
Le résultat suivant s'affiche, ce qui vous permet de définir les informations d'identification par défaut pour Snap Creator Server :

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. Entrez les informations appropriées pour chaque entrée.
+
Une fois que vous avez saisi votre entrée pour l'entrée Config name, les informations d'identification sont enregistrées et le message suivant s'affiche : INFO : les informations d'identification de l'interface de ligne de commande sont stockées avec succès. Les informations d'identification sont stockées dans le fichier snapcreator.credentials dans le répertoire ou le dossier .snapcreatorDirectory dans le répertoire de départ.

. Si vous souhaitez supprimer les informations d'identification stockées, supprimez le fichier snapcreator.Credentials.

