---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, windows 
summary: Vous pouvez effectuer la mise à niveau à partir de Snap Creator Server 4.1.x sur Windows. 
---
= Mise à niveau de Snap Creator Server 4.1.x sous Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer la mise à niveau à partir de Snap Creator Server 4.1.x sur Windows.

* Vous devez avoir arrêté les services Snap Creator (`snapcreatorserverservice` et `snapcreatoragentservice`) Avant de sauvegarder les répertoires Snap Creator pour s'assurer que les données sauvegardées sont complètes.
+
Par exemple, vous pouvez utiliser le composant logiciel enfichable Services pour arrêter les services :

+
.. Sélectionnez *Démarrer* > *Exécuter* et saisissez `services.msc`.
.. Recherchez et sélectionnez le service Snap Creator, puis arrêtez le service. Vous pouvez également ouvrir une invite de commandes et entrer les commandes suivantes :


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* Vous devez avoir sauvegardé les répertoires suivants ainsi que tous les sous-répertoires et fichiers associés dans le sous-répertoire Snap Creator 4.1.x Server Engine (C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine) :
+
** Base de données Snap Creator (..\snapcreator)
** Propriétés du serveur Snap Creator (..\etc.)
** Fichiers de configuration (..\configs)
** Journaux (...\logs)
** Référentiel de plug-in, si activé (..\snapcreatorPlugin)


* (Facultatif) si Snap Creator Agent est installé sur le même hôte que Snap Creator Server, vous devez sauvegarder les répertoires suivants et tous les sous-répertoires et fichiers associés dans le répertoire Snap Creator Agent (C:\Program Files\NetApp\Snap_Creator_Framework\scAgent4.1.x) :
+
** Propriétés de Snap Creator Agent (..\etc), qui contient les fichiers allowed_commands.config et agent.properties
** Journaux (...\logs)
** Plug-ins (..\plugins)


* Si Snap Creator a été démarré manuellement à partir d'une invite de commande, vous devez fermer l'invite de commande et l'arrêter.
+

NOTE: Si Snap Creator a été démarré à partir d'un service, le programme de désinstallation arrête ce service.



Les chemins fournis dans les étapes suivantes font référence au chemin d'installation par défaut pour Windows. Les informations sur le chemin d'accès peuvent différer de votre chemin d'installation si les valeurs par défaut n'ont pas été utilisées.

Une fois le processus de mise à niveau terminé, prenez en compte les problèmes suivants :

* Si la base de données Snap Creator mise à niveau contient certaines tâches marquées comme « en cours », l'état reste le même, même après la fin du processus de mise à niveau.
* L'administrateur par défaut du dernier Snap Creator doit être administrateur dans Snap Creator 4.1.
+
Si l'utilisateur 4.1.x n'est pas un administrateur, la mise à niveau affecte un rôle d'opérateur à l'utilisateur 4.1.x.

+
.. Arrêtez les services Snap Creator si vous ne l'avez pas encore fait.
+
Pour plus d'informations sur l'arrêt des services, reportez-vous aux détails fournis plus haut dans cette rubrique.

.. Désinstallez Snap Creator (pour Windows) en sélectionnant *Démarrer* > *programmes* > *Snap Creator* > *Désinstaller NetApp Snap Creator Framework*.
+
Pour plus d'informations, reportez-vous aux informations sur la désinstallation de Snap Creator sous Windows.

.. Installez la dernière version de Snap Creator Server.
+
Pour plus de détails, consultez les informations sur l'installation de Snap Creator Server sous Windows.

.. Si vous avez choisi de démarrer Snap Creator Server en tant que service après avoir installé le dernier Snap Creator Server, arrêtez le service.
+
Pour plus d'informations sur l'arrêt du service, reportez-vous aux détails fournis plus haut dans cette rubrique.

.. Supprimez le dernier dossier de base de données Snap Creator Server à l'adresse C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\snapcreator).
.. Copiez le répertoire de base de données Snap Creator 4.1 sauvegardé au dernier emplacement le plus récent, à l'adresse C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\snapcreator).
.. Copiez le répertoire de configuration Snap Creator 4.1 sauvegardé au dernier emplacement, à l'adresse C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\configs).
.. Copiez le répertoire des journaux Snap Creator 4.1 sauvegardés vers le dernier emplacement, à l'adresse C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\ENGINE\logs).
.. Ouvrez une invite de commandes et remplacez le répertoire par le sous-répertoire moteur dans le chemin d'installation de Snap Creator à l'adresse C:\Program Files\NetApp\Snap_Creator_Framework\SCServer4.1.x\ENGINE).
.. Mettez à niveau Snap Creator en entrant la commande suivante : java -jar snapcreator.jar -upgrade




Une fois le processus de mise à niveau terminé, démarrez le service Snap Creator Server à l'aide de l'une des méthodes suivantes :

* Utilisez le composant logiciel enfichable Services et démarrez le service.
* Depuis une invite de commande, entrez la commande suivante :
+
[listing]
----
sc start snapcreatorserverservice
----


Vous devez également valider le démarrage de l'interface graphique Snap Creator Framework en accédant à l'hôte local sur le port spécifié (https://IP_address:gui_port)[].

Vous devez vous connecter via HTTPS ; sinon, la connexion n'est pas redirigée automatiquement vers une connexion HTTPS et l'interface utilisateur ne fonctionnera pas.
