---
permalink: installation/task_creating_symbolic_links_for_domino_plug_in_on_linux_and_solaris_hosts.html 
sidebar: sidebar 
keywords: creating, create, symbolic, links, domino, plug-in, linux, solaris, hosts 
summary: Vous devez effectuer cette procédure si vous souhaitez créer des liens symboliques pour le plug-in Domino sur les hôtes Linux et Solaris. 
---
= Création de liens symboliques pour le plug-in Domino sur les hôtes Linux et Solaris
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez effectuer cette procédure si vous souhaitez créer des liens symboliques pour le plug-in Domino sur les hôtes Linux et Solaris.

Vous ne devez pas copier et coller des commandes directement à partir de ce document ; des erreurs peuvent survenir (comme des caractères mal transférés provoqués par des sauts de ligne et des retours papier). Copiez et collez les commandes dans un éditeur de texte, vérifiez les commandes, puis saisissez-les dans la console de l'interface de ligne de commande.


NOTE: Les chemins fournis dans les étapes suivantes font référence aux systèmes 32 bits ; les systèmes 64 bits doivent créer simlinks vers /usr/lib64 au lieu de /usr/lib.

. Ajoutez des liens vers /usr/lib pour les fichiers suivants :
+
** libxmlproc.so
** libndgts.so
** libnotes.so
** Libgsk8iccs.so (pour Domino 9.0 ou version ultérieure uniquement) Une méthode typique de création d'un lien symbolique consiste à utiliser la commande ln :


+
ln -s /chemin/vers/fichier_source /usr/lib/linked_file

+
+ où :

+
** -s indique au système d'exploitation de créer un lien symbolique.
** /Path/to/source_file est le chemin d'accès à l'un des fichiers de bibliothèque Domino, y compris le nom du fichier.
** linked_file est le nom du fichier en cours de liaison.
+
[listing]
----
ln -s /opt/ibm/domino/notes/latest/linux/libxmlproc.so /usr/lib/libxmlproc.so
ln -s /opt/ibm/domino/notes/latest/linux/libndgts.so /usr/lib/libndgts.so
ln -s /opt/ibm/domino/notes/latest/linux/libnotes.so /usr/lib/libnotes.so
ln -s /opt/ibm/domino/notes/latest/linux/libgsk8iccs.so /usr/lib/libgsk8iccs.so
----


. Vérifiez le chemin d'accès aux fichiers répertoriés à l'étape 1.

