---
permalink: installation/task_upgrading_the_snap_creator_server_3_6_x_on_unix.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 3.6.x, unix, unix-based 
summary: Vous pouvez effectuer la mise à niveau directement depuis Snap Creator Server 3.6.x sur des systèmes UNIX. 
---
= Mise à niveau de Snap Creator Server 3.6.x sur des systèmes UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer la mise à niveau directement depuis Snap Creator Server 3.6.x sur des systèmes UNIX.

* Si vous avez des noms d'utilisateur contenant des caractères spéciaux dans Snap Creator, vous devez avoir renommé ces utilisateurs en utilisant uniquement des caractères alphabétiques (a-z, A-Z) avant d'effectuer la mise à niveau.
* Vous avez arrêté les processus Snap Creator avant de sauvegarder les répertoires Snap Creator pour vous assurer que les données sauvegardées sont bien terminées.
+
Par exemple, entrez les commandes suivantes :

+
[listing]
----
/install_path/scServer3.6.x/bin/scServer stop
/install_path/scAgent3.6.x/bin/scAgent stop
----
* Vous avez sauvegardé les répertoires suivants et tous les sous-répertoires et fichiers associés dans le répertoire Snap Creator 3.6.x Server (/chemin_installation/sServer3.6.x) :
+
** Base de données Snap Creator (../gui/snapcreator)
** Profils et fichiers de configuration (../configs)
** Journaux (../logs) *Remarque :* ne supprimez pas les copies de sauvegarde Snap Creator 3.6.x que vous avez créées.




Les chemins fournis dans les étapes suivantes font référence au chemin d'installation par défaut. Le chemin d'accès dans les commandes ci-dessous peut différer de votre chemin d'installation.

Une fois le processus de mise à niveau terminé, prenez en compte les problèmes suivants :

* Si la base de données Snap Creator mise à niveau contient certaines tâches marquées comme « en cours », l'état reste le même, même après la fin du processus de mise à niveau.
* L'administrateur par défaut du dernier Snap Creator doit être un administrateur dans Snap Creator 3.6.x. Si l'utilisateur 3.6.x n'est pas un administrateur, la mise à niveau affecte un rôle d'opérateur à l'utilisateur 3.6.x.
+
.. Arrêtez les processus Snap Creator si ce n'est pas déjà fait.
+
Pour plus d'informations sur l'arrêt des processus, reportez-vous aux détails fournis plus haut dans cette rubrique.

.. Installez la dernière version de Snap Creator, mais ne démarrez pas le service Snap Creator Server.
+
Pour plus de détails, reportez-vous aux informations sur l'installation de Snap Creator Server sous UNIX.

.. Copiez le répertoire de base de données Snap Creator 3.6.x sauvegardé vers le dernier emplacement de base de données (/install_path/scServer4.1.x/Engine/snapcreator).
.. Copiez les profils et le dossier de configuration Snap Creator 3.6.x sauvegardés vers le dernier emplacement (/install_path/scServer4.1.x/Engine/configurations).
.. Copiez le dossier des journaux Snap Creator 3.6.x sauvegardé à l'emplacement le plus récent (/install_path/scServer4.1.x/Engine/logs).
.. Accédez au sous-répertoire du moteur dans le chemin d'installation de Snap Creator (/install_path/sServer4.1.x/Engine).
.. Mettez à niveau Snap Creator en entrant la commande suivante : java -jar snapcreator.jar -upgrade




Une fois le processus de mise à niveau terminé, démarrez le service Snap Creator Server en entrant la commande suivante :

/Chemin_installation/serveur_SCServer4.1.x/bin/serveur_scServer démarrer

Supprimez également le répertoire d'installation de Snap Creator 3.6.x.


IMPORTANT: Ne supprimez pas vos copies de sauvegarde tant que vous n'êtes pas certain d'avoir à revenir à une version antérieure.

Vous devez également valider le démarrage de l'interface graphique Snap Creator Framework en accédant à l'hôte local sur le port spécifié (https://IP_address:gui_port)[].

Vous devez vous connecter via HTTPS ; sinon, la connexion n'est pas redirigée automatiquement vers une connexion HTTPS et l'interface utilisateur ne fonctionnera pas.

*Informations connexes*

xref:task_installing_the_snap_creator_server_on_unix.adoc[Installation de Snap Creator Server sur des systèmes UNIX]
