---
permalink: installation/task_uninstalling_snap_creator_server_on_unix.html 
sidebar: sidebar 
keywords: uninstalling, uninstall, snap, creator, server, unix 
summary: 'Vous pouvez désinstaller Snap Creator Server d"UNIX en supprimant le dossier d"installation de Snap Creator Server.' 
---
= Désinstallation de Snap Creator Server sous UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désinstaller Snap Creator Server d'UNIX en supprimant le dossier d'installation de Snap Creator Server.

Sauvegardez les répertoires suivants, ainsi que tous les sous-répertoires et fichiers associés, dans le répertoire du moteur Snap Creator Server (/install_path/scServer4.1.0/Engine) :

* Base de données Snap Creator (../snapcreator)
* Propriétés du serveur Snap Creator (../etc.)
* Configuration (../configurations)
* Journaux (.../logs)
* Référentiel de plug-in, si activé (../snapcreatorPlugin)



NOTE: Assurez-vous de sauvegarder ces répertoires ; sinon, vous perdrez les données utilisateur et ne pourrez pas les récupérer.

Pour désinstaller Snap Creator Server, effectuez les opérations suivantes.


NOTE: Les chemins fournis dans les étapes suivantes font référence au chemin d'installation générique. Vous pouvez modifier le chemin d'accès dans ces commandes pour refléter le chemin d'installation personnalisé de Snap Creator Server.

. Arrêtez le service Snap Creator Server (`snapcreatorserverservice`) à l'aide du script suivant :
+
[listing]
----
/install_path/scServer4.1.0/bin/scServer stop
----
. Supprimez le dossier d'installation de Snap Creator Server.
+
Par exemple, pour un système Linux, exécutez la commande suivante :

+
[listing]
----
rm -Rf /install_path/scServer4.1.0
----

